#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define RPL_CONF_DIO_INTERVAL_MIN 8
#define RPL_CONF_DIO_INTERVAL_DOUBLINGS 6
#define UIP_CONF_MAX_ROUTES 128
#define NBR_TABLE_CONF_MAX_NEIGHBORS 64

#endif /* PROJECT_CONF_H_ */
